### PR TITLE
[UPD] Routing: make possible to run routing via cli

### LINKED ISSUE #68: Routing via cli, does not work
while try to exceute the application via cli the routing does not change it stack in the first page, but path on the browser is chnging

### PR DESCRIPTION
**Pull request by bim-g**
closes #68

### CODE REVIEW

File: src/Core/Routing/Router.php [hunk 1]
```diff
@@ -13,26 +13,10 @@ class  Router
...
-        $this->routes=[];
-        $this->_nameRoute=[];
-        $this->_url=$this->getMethodeUrl();
-    }
-
-    /**
-     * scan for url to match
-     * @return mixed|void
-     */
-    private function getMethodeUrl(){
```
Comment (bim-g) [inline src/Core/Routing/Router.php:26]: remove uselless method

File: src/Core/Routing/Router.php [hunk 2]
```diff
@@ -13,26 +13,10 @@ class  Router
...
-        foreach($_GET as $url) return $url;
```
Comment (bim-g) [inline src/Core/Routing/Router.php:27]: This bloc the app to be executed via CLI

**Review by bim-g — COMMENTED** [review]
Run app rpoject via CLI
