### PR TITLE
[FIX] error message while using asc or desc without order by.

### LINKED ISSUE #151: Exception error while using ASC whithout providing order by
While doing a select from a table and call from ASC or DESC without providing which field to order by, it generate an error message.
`  'exception' => string 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ASC  LIMIT 10' at line 1' (length=215)`

### PR DESCRIPTION
**Pull request by bim-g**
Each time we try to use 'ASC' or 'DESC' without specifying the order by field we get an error.
closes #151

### CODE REVIEW

File: config/init.php [hunk 1]
```diff
@@ -61,7 +61,7 @@ function serverDomain(): object
  *  Project autoload register
  */
 require_once $ROOT_DIR . '/config/autoload.php';
-require_once $ROOT_DIR . '/vendor/autoload.php';
+//require_once $ROOT_DIR . '/vendor/autoload.php';
```
Comment (bim-g) [inline config/init.php:64]: This should be revised.
