### PR TITLE
[FIX] group middleware return empty array

### LINKED ISSUE #106: Group middleware does not work
I tried to implement group middleware but surprisingly it does not work, but route middleware is working fine.

### PR DESCRIPTION
**Pull request by bim-g**
The groupe routing does not work as expected.
closes #106

### CODE REVIEW

File: src/Core/Routing/Router.php [hunk 1]
```diff
@@ -95,7 +95,6 @@ private function add(string $pattern, $callable, ?string $name, string $methode)
         if ($name) {
             $this->_nameRoute[$name] = $route;
         }
-        $this->baseMiddleware = null;
```
Comment (bim-g) [inline src/Core/Routing/Router.php:98]: You have to assume there could not be another problem while creating multiple groupe

**Review by bim-g — COMMENTED** [review]
Check the process
