### PR TITLE
[FIX] fix error call not defined method.

### LINKED ISSUE #126: Only the first characters of the method link relation should in lowercase
While call the method relation of two entity the first Caracter should be only in lower case to respect the pascal case on the method for entity with a long name.

### PR DESCRIPTION
**Pull request by bim-g**
There was an error where you pascal case on class or class method, which lead to some confusion. so only the first Caracter of the class will be set to lowercase in case the method class is in pascal case.
close #126

### CODE REVIEW

File: controller/exampleController.php [hunk 1]
```diff
@@ -12,7 +12,7 @@
 use Wepesi\Core\Redirect;
 use Wepesi\Core\Session;
 
-class homeController{
+class exampleController{
```
Comment (bim-g) [inline controller/exampleController.php:15]: This is better

**Review by bim-g — COMMENTED** [review]
Nice
