### PR TITLE
[Fix] this module make the validation return false result while the condition where exact.

### LINKED ISSUE #98: Validation problem
The `positiveParamMethod, should be checked as false in case the value to rules value is negative.
This make the validation to be false.

### PR DESCRIPTION
**Pull request by bim-g**
While validate a schema, in case the condition where meet unexpectedly it return error, but when the condition is not met it passed, which was confusing. the problem come from a module that help to validate positive value.
closes #98

### CODE REVIEW

File: src/Core/Validation/Providers/ValidatorProvider.php [hunk 1]
```diff
@@ -117,17 +117,17 @@ public function result(): array
      * @param bool $max
      * @return bool
      */
-    protected function positiveParamMethod(int $rule, bool $max = false): bool
+    protected function checkNotPositiveParamMethod(int $rule, bool $max = false): bool
```
Comment (bim-g) [inline src/Core/Validation/Providers/ValidatorProvider.php:120]: To rename the module help make more sens.

**Review by bim-g — COMMENTED** [review]
Nice
