### PR TITLE
[ENH] get formatted route path via function

### LINKED ISSUE #173: Fatal error: Uncaught Error: Undefined constant "Wepesi\Core\fals" in \working on\doctawetu_project\doctawetuapp\src\Core\MetaData.php on line 270
Typo error of data type passed to the parameter 'false` instead of `fals`.

### LINKED ISSUE #174: Fatal error: Uncaught Error: try to access Undefined  "parentNode" in "\doctawetuapp\src\Core\Views.php on line 226 bug
This bugs happen when we try to include not well formatted html content as text, and it can not specify if there is a parent node of the content.

### LINKED ISSUE #175: Have a method to help enter clean route path will be helpfull
Each time we want to enter a route we need to write like `WEB_ROOT . 'articles/nice-admin'`
while it could be good to only write ` '/articles/nice-admin'`.
I think the proposition is to have a method that could help resolve such problems and avoid many problems.

### PR DESCRIPTION
**Pull request by bim-g**
In this PR, we made so much solution to resolved problem from typo error as params,
with a clean route path as simple to write with a function instead of trying to thing   how to write each link to feat the need.

[FIX] fixing type 'false' instead of 'fals']
closes #173 

[FIX] resolve try to access parentNode of undefined]
closes #174 

[ENH] get formatted route path via function]
closes #175

### CODE REVIEW

File: config/function.php [hunk 1]
```diff
@@ -119,4 +119,13 @@ function tra(string $message, $value = null): string
...
     $translate_value = !is_array($value) ? [$value] : $value;
     return $i18n->translate($message, $translate_value);
+}
+
+/**
+ * get a formatted application route path
+ * @param string $path
+ * @return string
+ */
+function route_path(string $path): string{
```
Comment (bim-g) [inline config/function.php:129]: Like the idea, simple and clear
