### PR TITLE
[FIX] View: missing file to render

### LINKED ISSUE #46: Problem with View render when missing view file to render.
There is parse error message not good, and dificulte to understand when the view file to rendre is not available.
there should be a better message to be display.

### PR DESCRIPTION
**Pull request by bim-g**
Problem resolved
closes #46

### CODE REVIEW

File: src/Core/View.php [hunk 1]
```diff
@@ -6,6 +6,7 @@ class View{
         private array $data=[];
         const ERROR=ROOT."views/404.php";
         private string $render=self::ERROR;
+        private $i18n;
```
Comment (bim-g) [inline src/Core/View.php:9]: Should be remove, until the i18n is not yest suported

File: src/Core/View.php [hunk 2]
```diff
@@ -21,6 +22,10 @@ function assign(string $variable,$value){
         function __destruct()
         {
             extract($this->data);
-            include($this->render);
+            if (is_file($this->render)) {
+                include($this->render);
+            }else{
+                print_r(["exception"=>"file path is not correct.?"]);
```
Comment (bim-g) [inline src/Core/View.php:28]: what is the intserest of using array?
