### PR TITLE
[Fix] fix where condition cast field value.

### LINKED ISSUE #99: Wherebuilder condition problem
There is another cast that block access to the field value while checking if the value is trying or integer on `conditionIsSteing` method

### PR DESCRIPTION
**Pull request by bim-g**
There is a problem while writing where conditions, there is another cast that add extra information to the field value that will make the condition to return false or empty for some case.
closes #99

### CODE REVIEW

File: src/Core/Validation/Schema/StringSchema.php [hunk 1]
```diff
@@ -60,7 +60,7 @@ public function match(string $key_to_match): StringSchema
     }
 
     /**
-     * @param string $ip_address
+     * @param bool $ipv6
```
Comment (bim-g) [inline src/Core/Validation/Schema/StringSchema.php:63]: Good precision

**Review by bim-g — COMMENTED** [review]
LGTM
